package de.uni_stuttgart.iaas.servicewrapper.opalxyzr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:09.398+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "OpalXyzrService", 
                  wsdlLocation = "file:/D:/TraDE/GitHub/trade-opalXYZR-wrapper/src/main/resources/opalXYZR.wsdl",
                  targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/") 
public class OpalXyzrService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/", "OpalXyzrService");
    public final static QName OpalXyzrServicePort = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/", "OpalXyzrServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/TraDE/GitHub/trade-opalXYZR-wrapper/src/main/resources/opalXYZR.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OpalXyzrService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/TraDE/GitHub/trade-opalXYZR-wrapper/src/main/resources/opalXYZR.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OpalXyzrService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OpalXyzrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpalXyzrService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OpalXyzrService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OpalXyzrService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OpalXyzrService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OpalXYZR
     */
    @WebEndpoint(name = "OpalXyzrServicePort")
    public OpalXYZR getOpalXyzrServicePort() {
        return super.getPort(OpalXyzrServicePort, OpalXYZR.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpalXYZR
     */
    @WebEndpoint(name = "OpalXyzrServicePort")
    public OpalXYZR getOpalXyzrServicePort(WebServiceFeature... features) {
        return super.getPort(OpalXyzrServicePort, OpalXYZR.class, features);
    }

}
