package de.uni_stuttgart.iaas.servicewrapper.opalxyzr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:09.386+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "OpalXYZRCallbackService", 
                  wsdlLocation = "file:/D:/TraDE/GitHub/trade-opalXYZR-wrapper/src/main/resources/opalXYZR.wsdl",
                  targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/") 
public class OpalXYZRCallbackService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/", "OpalXYZRCallbackService");
    public final static QName OpalXYZRCallbackServicePort = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/", "OpalXYZRCallbackServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/TraDE/GitHub/trade-opalXYZR-wrapper/src/main/resources/opalXYZR.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OpalXYZRCallbackService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/TraDE/GitHub/trade-opalXYZR-wrapper/src/main/resources/opalXYZR.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OpalXYZRCallbackService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OpalXYZRCallbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpalXYZRCallbackService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OpalXYZRCallbackService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OpalXYZRCallbackService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OpalXYZRCallbackService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OpalXYZRCallback
     */
    @WebEndpoint(name = "OpalXYZRCallbackServicePort")
    public OpalXYZRCallback getOpalXYZRCallbackServicePort() {
        return super.getPort(OpalXYZRCallbackServicePort, OpalXYZRCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpalXYZRCallback
     */
    @WebEndpoint(name = "OpalXYZRCallbackServicePort")
    public OpalXYZRCallback getOpalXYZRCallbackServicePort(WebServiceFeature... features) {
        return super.getPort(OpalXYZRCallbackServicePort, OpalXYZRCallback.class, features);
    }

}
