
package de.uni_stuttgart.iaas.servicewrapper.opalxyzr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:09.357+01:00
 * Generated source version: 3.1.12
 * 
 */
public final class OpalXYZR_OpalXyzrServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/", "OpalXyzrService");

    private OpalXYZR_OpalXyzrServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OpalXyzrService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OpalXyzrService ss = new OpalXyzrService(wsdlURL, SERVICE_NAME);
        OpalXYZR port = ss.getOpalXyzrServicePort();  
        
        {
        System.out.println("Invoking runOpalXYZR...");
        de.uni_stuttgart.iaas.servicewrapper.opalxyzr.RunOpalXyzr _runOpalXYZR_parameters = null;
        de.uni_stuttgart.iaas.servicewrapper.opalxyzr.RunOpalXyzrResponse _runOpalXYZR__return = port.runOpalXYZR(_runOpalXYZR_parameters);
        System.out.println("runOpalXYZR.result=" + _runOpalXYZR__return);


        }

        System.exit(0);
    }

}
