
package de.uni_stuttgart.iaas.servicewrapper.opalxyzr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:09.346+01:00
 * Generated source version: 3.1.12
 * 
 */
public final class OpalXYZRCallback_OpalXYZRCallbackServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/", "OpalXYZRCallbackService");

    private OpalXYZRCallback_OpalXYZRCallbackServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OpalXYZRCallbackService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OpalXYZRCallbackService ss = new OpalXYZRCallbackService(wsdlURL, SERVICE_NAME);
        OpalXYZRCallback port = ss.getOpalXYZRCallbackServicePort();  
        
        {
        System.out.println("Invoking callbackXYZR...");
        de.uni_stuttgart.iaas.servicewrapper.opalxyzr.Callback _callbackXYZR_parameters = null;
        port.callbackXYZR(_callbackXYZR_parameters);


        }

        System.exit(0);
    }

}
