package de.uni_stuttgart.iaas.servicewrapper.opalxyzr;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:49:09.373+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/", name = "opalXYZRCallback")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OpalXYZRCallback {

    @WebMethod(action = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/callbackXYZR")
    @Oneway
    public void callbackXYZR(
        @WebParam(partName = "parameters", name = "callback", targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalXYZR/")
        Callback parameters
    );
}
